// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cli/v0/cli.proto

// The cli.v0 options let a proto's owner shape the CLI generated from it;
// without them, every name derives from the proto.

package cliv0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceOptions shapes the command a service generates.
type ServiceOptions struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_cli_v0_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v0_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceOptions) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ServiceOptions) SetName(v string) {
	x.xxx_hidden_Name = v
}

type ServiceOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name replaces the derived command name.
	Name string
}

func (b0 ServiceOptions_builder) Build() *ServiceOptions {
	m0 := &ServiceOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

// CommandOptions shapes the subcommand an rpc generates.
type CommandOptions struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandOptions) Reset() {
	*x = CommandOptions{}
	mi := &file_cli_v0_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOptions) ProtoMessage() {}

func (x *CommandOptions) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v0_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommandOptions) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *CommandOptions) SetName(v string) {
	x.xxx_hidden_Name = v
}

type CommandOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// name replaces the derived subcommand name.
	Name string
}

func (b0 CommandOptions_builder) Build() *CommandOptions {
	m0 := &CommandOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

var file_cli_v0_cli_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         86471,
		Name:          "cli.v0.service",
		Tag:           "bytes,86471,opt,name=service",
		Filename:      "cli/v0/cli.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*CommandOptions)(nil),
		Field:         86471,
		Name:          "cli.v0.command",
		Tag:           "bytes,86471,opt,name=command",
		Filename:      "cli/v0/cli.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional cli.v0.ServiceOptions service = 86471;
	E_Service = &file_cli_v0_cli_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional cli.v0.CommandOptions command = 86471;
	E_Command = &file_cli_v0_cli_proto_extTypes[1]
)

var File_cli_v0_cli_proto protoreflect.FileDescriptor

const file_cli_v0_cli_proto_rawDesc = "" +
	"\n" +
	"\x10cli/v0/cli.proto\x12\x06cli.v0\x1a google/protobuf/descriptor.proto\"$\n" +
	"\x0eServiceOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x0eCommandOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:S\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18ǣ\x05 \x01(\v2\x16.cli.v0.ServiceOptionsR\aservice:R\n" +
	"\acommand\x12\x1e.google.protobuf.MethodOptions\x18ǣ\x05 \x01(\v2\x16.cli.v0.CommandOptionsR\acommandB8Z6github.com/braveokafor/proto-to-cli/proto/cli/v0;cliv0b\x06proto3"

var file_cli_v0_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cli_v0_cli_proto_goTypes = []any{
	(*ServiceOptions)(nil),              // 0: cli.v0.ServiceOptions
	(*CommandOptions)(nil),              // 1: cli.v0.CommandOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
}
var file_cli_v0_cli_proto_depIdxs = []int32{
	2, // 0: cli.v0.service:extendee -> google.protobuf.ServiceOptions
	3, // 1: cli.v0.command:extendee -> google.protobuf.MethodOptions
	0, // 2: cli.v0.service:type_name -> cli.v0.ServiceOptions
	1, // 3: cli.v0.command:type_name -> cli.v0.CommandOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cli_v0_cli_proto_init() }
func file_cli_v0_cli_proto_init() {
	if File_cli_v0_cli_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cli_v0_cli_proto_rawDesc), len(file_cli_v0_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_cli_v0_cli_proto_goTypes,
		DependencyIndexes: file_cli_v0_cli_proto_depIdxs,
		MessageInfos:      file_cli_v0_cli_proto_msgTypes,
		ExtensionInfos:    file_cli_v0_cli_proto_extTypes,
	}.Build()
	File_cli_v0_cli_proto = out.File
	file_cli_v0_cli_proto_goTypes = nil
	file_cli_v0_cli_proto_depIdxs = nil
}
